### ISSUE TITLE
aarch64 docker image cannot register user

### ISSUE THREAD

**Issue by 5high** [mprasil/docker-bitwarden#6]
When complet run bitwarden_rs open web portal regist user , fill all of information click ok , but nothing happend , the page no error and no success information give to me.

anyone can help me ?

**Comment by mprasil** [comment]
I see you already realized, that this is not the correct project for this issue, for anyone else you can follow the proper issue [here](https://github.com/dani-garcia/bitwarden_rs/issues/472).
